# -*- coding: utf-8 -*-
"""studentgrade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqRRPdBOuj-dFxw1f5y2LHhm0_W6iG7y
"""

USERNAME = "teacher"
PASSWORD = "1234"

print("=== Student Grade Book Login ===")
user = input("Username: ")
pwd = input("Password: ")

if user != USERNAME or pwd != PASSWORD:
    print("Invalid login!")
    exit()

print("\nLogin successful!\n")
name = input("Enter student name: ")
roll = input("Enter roll number: ")
total_classes = int(input("Total classes held: "))
attended = int(input("Classes attended: "))
attendance_percentage = (attended / total_classes) * 100
subjects = ["Maths", "Physics", "Chemistry", "English", "Computer"]
marks = []
for sub in subjects:
    m = int(input(f"Enter marks for {sub}: "))
    marks.append(m)
total_marks = sum(marks)
average = total_marks / len(subjects)
percentage = average
if percentage >= 90:
    grade = "A+"
    gpa = 10
elif percentage >= 80:
    grade = "A"
    gpa = 9
elif percentage >= 70:
    grade = "B"
    gpa = 8
elif percentage >= 60:
    grade = "C"
    gpa = 7
elif percentage >= 50:
    grade = "D"
    gpa = 6
else:
    grade = "F"
    gpa = 0
if grade in ["A+", "A"]:
    remark = "Excellent performance"
elif grade == "B":
    remark = "Good, can improve"
elif grade == "C":
    remark = "Average performance"
elif grade == "D":
    remark = "Needs improvement"
else:
    remark = "Fail, needs serious effort"
print("\n========== REPORT CARD ==========")
print("Name:", name)
print("Roll No:", roll)
print("Attendance:", f"{attendance_percentage:.2f}%")
print("\nSubject-wise Marks:")
for i in range(len(subjects)):
    print(subjects[i], ":", marks[i])
print("\nTotal Marks:", total_marks)
print("Percentage:", f"{percentage:.2f}%")
print("Grade:", grade)
print("GPA:", gpa)
print("Remarks:", remark)
print("================================")